name: go-ci
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  mod:
    name: Mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}--gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go mod download
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [mod]
    env:
      GOCACHE: "/tmp/go/cache"
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v1
      - uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-
      - uses: actions/cache@v2.1.6
        with:
          path: /tmp/go/cache
          key: ${{ runner.os }}-go-build-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-build-${{ github.ref }}-
            ${{ runner.os }}-go-build-
      - run: go build -o anke-two
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: anke-two
          path: anke-two
    # test:
    #     name: Test
    #     runs-on: ubuntu-latest
    #     needs: [mod]
      #     services:
        #       mysql:
        #        image: mariadb:10.3.9
            #        ports:
        #          - 3306:3306
          #         env:
          #           MYSQL_ROOT_PASSWORD: password
    #           MYSQL_DATABASE: anke-two
      #     steps:
        #       - uses: actions/setup-go@v2
          #         with:
      #           go-version: 1.17
      #   #       - uses: actions/checkout@v2
        #       - uses: actions/cache@v2.1.6
          #         with:
          #           path: ~/go/pkg/mod
          #           key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
            #           restore-keys: |
      #             ${{ runner.os }}-gomod-
      #       - run: go install github.com/golang/mock/mockgen@v1.5.0
      #       - run: go generate ./...
        #       - run: go test ./... -v -coverprofile=coverage.txt -race -vet=off
          #         env:
          #           MARIADB_USERNAME: root
          #           MARIADB_PASSWORD: password
          #           MARIADB_HOSTNAME: 127.0.0.1
      #           MARIADB_DATABASE: anke-two
        #       - name: Upload coverage data
        #         uses: codecov/codecov-action@v2.1.0
          #         with:
          #           file: ./coverage.txt
      #           yml: ./codecov.yml
        #       - uses: actions/upload-artifact@v2.2.4
          #         with:
          #           name: coverage.txt
  #           path: coverage.txt #/
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2.0.2
        with:
          reporter: github-pr-check
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
  spectral:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spectral checks
        uses: stoplightio/spectral-action@v0.8.1
        with:
          file_glob: docs/swagger/*.yaml
          repo_token: ${{ secrets.GITHUB_TOKEN }}